"""Compatibility aliases for the renamed Research Plan generator.

The public API kept the old roadmap routes during the product rename. Import
aliases stay here for scripts/tests that still reference the original module.
"""

from backend.research_plan_generator import PAPER_GUIDANCE_CACHE as PAPER_ROADMAP_CACHE
from backend.research_plan_generator import RESEARCH_PLAN_CACHE as ROADMAP_CACHE
from backend.research_plan_generator import build_paper_guidance_prompt as build_paper_roadmap_prompt
from backend.research_plan_generator import build_research_plan_context as build_roadmap_context
from backend.research_plan_generator import build_research_plan_prompt as build_roadmap_prompt
from backend.research_plan_generator import generate_paper_guidance as generate_paper_roadmap
from backend.research_plan_generator import generate_research_plan as generate_roadmap
from backend.research_plan_generator import paper_guidance_cache_key as paper_roadmap_cache_key
from backend.research_plan_generator import paper_guidance_cache_status as paper_roadmap_cache_status
from backend.research_plan_generator import research_plan_cache_key as roadmap_cache_key
from backend.research_plan_generator import research_plan_cache_status as roadmap_cache_status
from backend.research_plan_generator import stream_research_plan as stream_roadmap

